# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4b7eee889fc36b8d807c1ed45456f9524e846a6c13221cae0deff50d6601d86541cdc5b1a24cb14897bdfc3c16d727423b5c7448910c46b8ab90f789163c4b3

test:
  secret_key_base: f1c7518cb6e55f3c15383194a5adc4d1e4dec34b9f20859f5585f8c88d5be6820fe98ecca62331db84df1b67f37ad09d27bd0d1be8a5ac2e9d570c1c1846ce53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
