# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca0efb350141d5020240fd9fd9bb984502507eaef31cdf35ab90530e60675094ad0e7a506ef1ee542d10a2196a054d34627dc841e896ad3bccaaa261d201f3e3

test:
  secret_key_base: 29302d2eb757d40e047c61db352f78f0130e4c5bede272c3641225d0021cf3b3eb7abbd72af5dc2ca740e0715f6ccbbece645b5dad95d0b34561cafff62f194c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
